#!/usr/bin/env bash
# Detects your Apple Development Team ID and writes it into Config/Signing.xcconfig,
# then regenerates the Xcode project. Run this AFTER signing into Xcode once
# (Xcode ▸ Settings ▸ Accounts ▸ add your Apple ID), which creates the cert.
set -euo pipefail
cd "$(dirname "$0")/.."

TEAM="$(security find-certificate -a -c "Apple Development" -p 2>/dev/null \
  | openssl x509 -noout -subject -nameopt multiline 2>/dev/null \
  | awk -F'= ' '/organizationalUnitName/ {print $2; exit}')"

if [ -z "${TEAM:-}" ]; then
  cat <<'MSG'
✗ No "Apple Development" certificate found.

  1. Open Xcode ▸ Settings ▸ Accounts and add your Apple ID (free is fine).
  2. Select the account, click "Manage Certificates…", press + ▸ "Apple Development".
  3. Re-run this script.
MSG
  exit 1
fi

echo "▸ Found Team ID: $TEAM"
cat > Config/Signing.xcconfig <<EOF
// Auto-generated by Scripts/set-team.sh
DEVELOPMENT_TEAM = $TEAM
CODE_SIGN_STYLE = Automatic
EOF
echo "▸ Wrote Config/Signing.xcconfig"

if command -v xcodegen >/dev/null 2>&1; then
  xcodegen generate
  echo "▸ Regenerated MusicGlass.xcodeproj"
fi
